# Generated by Django 2.2.2 on 2020-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(upload_to='banner_image/')),
                ('created_at', models.DateTimeField(editable=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
