version: '3.7'
services:
    cuppon-pro:
        env_file: "env/${ENV}.env"
        build:
            context: .
            dockerfile: dockerfiles/django/Dockerfile
        image: cuppon-pro
        entrypoint: ./scripts/run_web.sh
        depends_on:
        - db
        - rabbitmq
        volumes:
        - "media_volume:/app/media/"
        restart: unless-stopped
        networks:
        - cuppon-pro-net
        ports:
        - 8000

    db:
        env_file: "env/${ENV}.env"
        image: bitnami/postgresql:12.4.0
        volumes:
        - "persist_volume:/var/lib/postgresql/data"
        restart: unless-stopped
        networks:
        - cuppon-pro-net

    rabbitmq:
        env_file: "env/${ENV}.env"
        image: bitnami/rabbitmq:3.8.9
        restart: unless-stopped
        networks:
        - cuppon-pro-net

    celery:
        env_file: "env/${ENV}.env"
        image: cuppon-pro
        entrypoint: ./scripts/run_celery.sh
        volumes:
        - "media_volume:/app/media/"
        depends_on:
        - db
        - rabbitmq
        - cuppon-pro
        networks:
        - cuppon-pro-net
        restart: unless-stopped

networks:
    cuppon-pro-net:
        name: cuppon-pro-network
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"

volumes:
    persist_volume:
    media_volume:
