FEATURE_TYPES = {
    'CREATE': 1,
    'UPDATE': 2,
    'EXPORT': 3,
}

FEATURE_TYPE_CHOICES = (
    (FEATURE_TYPES['CREATE'], 'CREATE'),
    (FEATURE_TYPES['UPDATE'], 'UPDATE'),
    (FEATURE_TYPES['EXPORT'], 'EXPORT'),
)

FREQUENCY_UNIT_TYPES = {
    'HOURLY': 1,
    'DAILY': 2,
    'MONTHLY': 3,
}

FREQUENCY_UNIT_CHOICES = (
    (FREQUENCY_UNIT_TYPES['HOURLY'], 'HOURLY'),
    (FREQUENCY_UNIT_TYPES['DAILY'], 'DAILY'),
    (FREQUENCY_UNIT_TYPES['MONTHLY'], 'MONTHLY'),
)

FREQUENCY_USAGE_PREFERENCES = {
    'FREQUENCY': 1,
    'TIME': 2,
    'BOTH': 3,
}

FREQUENCY_USAGE_PREFERENCE_CHOICES = (
    (FREQUENCY_USAGE_PREFERENCES['FREQUENCY'], 'FREQUENCY'),
    (FREQUENCY_USAGE_PREFERENCES['TIME'], 'TIME'),
    (FREQUENCY_USAGE_PREFERENCES['BOTH'], 'BOTH'),
)
