# Generated by Django 2.2.8 on 2021-03-14 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0003_auto_20210314_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ORDERED', 'ORDERED'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED')], default='ORDERED', max_length=16)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('is_credit', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT')], default='CASH', max_length=10)),
                ('types', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('DISPATCH', 'DISPATCH'), ('RETURN', 'RETURN')], default='PURCHASE', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('stock', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14)),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('paid_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT')], default='CASH', max_length=10)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('payment_note', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stock'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('paid_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT')], default='CASH', max_length=10)),
                ('payment_note', models.CharField(blank=True, max_length=128, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expense_for', models.CharField(blank=True, max_length=128, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('is_refund', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
