# Generated by Django 2.2.8 on 2021-03-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210315_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='paid_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
