version: '3.7'
services:
    cupponpro-nginx:
        build:
            context: .
        image: cupponpro-nginx
        restart: unless-stopped
        networks:
        - cuppon-pro-net
        ports:
        - 7000:80
        - 7055:443

networks:
    cuppon-pro-net:
        name: cuppon-pro-network
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"
