# Generated by Django 2.2.8 on 2020-12-22 12:21

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFeatureSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=255)),
                ('feature_type', models.PositiveSmallIntegerField(choices=[(1, 'CREATE'), (2, 'UPDATE'), (3, 'EXPORT')], default=3)),
                ('column_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('frequency', models.IntegerField(default=1)),
                ('frequency_unit', models.PositiveSmallIntegerField(choices=[(1, 'HOURLY'), (2, 'DAILY'), (3, 'MONTHLY')], default=2)),
                ('generation_time', models.TimeField(blank=True, null=True)),
                ('usage_preference', models.PositiveSmallIntegerField(choices=[(1, 'FREQUENCY'), (2, 'TIME'), (3, 'BOTH')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
