# Generated by Django 2.2.8 on 2021-01-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filefeaturesettings',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='filefeaturesettings',
            old_name='modified_on',
            new_name='modified_at',
        ),
    ]
