# Generated by Django 2.2.8 on 2020-12-08 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.misc
import helpers.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('phone_number_ext', models.CharField(default='977', max_length=6, validators=[helpers.validators.is_numeric_value])),
                ('phone_number', models.CharField(max_length=12, validators=[helpers.validators.phone_number_validator, helpers.validators.is_numeric_value])),
                ('code', models.CharField(default=helpers.misc.make_hash_value, max_length=8)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('USER_REGISTER', 'User Registration'), ('RESET_PASSWORD', 'Reset Password'), ('CHANGE_PHONE_NUMBER', 'Change Phone number')], default='USER_REGISTER', max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Expired'), (1, 'Active'), (2, 'Inactive')], default=2)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
