# Generated by Django 2.2.8 on 2021-02-07 08:12

from django.db import migrations, models
import django.utils.timezone
import helpers.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210131_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone_number_ext', models.CharField(default='977', max_length=6, validators=[helpers.validators.is_numeric_value])),
                ('phone_number', models.CharField(max_length=12, validators=[helpers.validators.phone_number_validator, helpers.validators.is_numeric_value])),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
