# Generated by Django 2.2.8 on 2021-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210131_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
