# Generated by Django 2.2.8 on 2021-02-07 10:23

from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[helpers.validators.phone_number_validator, helpers.validators.is_numeric_value]),
        ),
    ]
