# Generated by Django 2.2.8 on 2021-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_user_is_obsolete'),
        ('userapp', '0008_auto_20210207_1608'),
    ]

    operations = [
    ]
