# Generated by Django 2.2.8 on 2021-03-03 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20210302_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='((?=.*[a-z])(?=.*[A-Z]))|((?=.*[A-Z])(?=.*[a-z]))|(?=.*[a-z])|(?=.*[A-Z])')]),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='((?=.*[a-z])(?=.*[A-Z]))|((?=.*[A-Z])(?=.*[a-z]))|(?=.*[a-z])|(?=.*[A-Z])')]),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
