# Generated by Django 2.2.8 on 2021-03-14 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.app_helpers
import helpers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[helpers.validators.is_alphanumeric_with_exception])),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to=helpers.app_helpers.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
        ),
    ]
