# Generated by Django 2.2.8 on 2020-12-13 17:02

from django.db import migrations, models
import django.utils.timezone
import helpers.app_helpers
import helpers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[helpers.validators.is_alphanumeric_with_exception])),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to=helpers.app_helpers.content_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
