# Generated by Django 2.2.8 on 2021-03-30 05:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.app_helpers
import helpers.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210318_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[helpers.validators.is_alphanumeric_with_exception])),
                ('commission', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('logo', models.ImageField(upload_to=helpers.app_helpers.content_file_name)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+?[\\d]{2,3}\\-?)?[\\d]{8,10}$')])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
