# Generated by Django 2.2.8 on 2021-02-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210225_1308'),
        ('company', '0002_follows'),
    ]

    operations = [
    ]
