# Generated by Django 2.2.8 on 2021-03-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'advertisements'},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
