# Generated by Django 2.2.8 on 2021-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210314_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('TOP', 'TOP'), ('BOTTOM', 'BOTTOM')], default='TOP', max_length=10),
        ),
    ]
