# Generated by Django 2.2.8 on 2021-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
