# Generated by Django 2.2.8 on 2021-03-17 06:26

from django.db import migrations, models
import django.db.models.deletion
import helpers.app_helpers
import helpers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'bulk quantities',
                'db_table': 'bulk_quantity',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True, validators=[helpers.validators.is_alphanumeric_with_exception])),
                ('description', models.CharField(max_length=250)),
                ('expiry_date', models.DateField()),
                ('token', models.CharField(editable=False, max_length=8)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], default='FLAT', max_length=12)),
                ('discount', models.FloatField(validators=[helpers.validators.is_positive_float])),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('deal_of_the_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_price', models.PositiveIntegerField(default=0)),
                ('purchase_currency', models.CharField(choices=[('NRS', 'NRS'), ('INR', 'INR'), ('USD', 'USD')], default='NRS', max_length=4)),
                ('selling_price', models.PositiveIntegerField()),
                ('selling_currency', models.CharField(choices=[('NRS', 'NRS'), ('INR', 'INR'), ('USD', 'USD')], default='NRS', max_length=4)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.CharField(editable=False, max_length=8)),
                ('types', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='', max_length=8, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to=helpers.app_helpers.content_file_name)),
                ('token', models.CharField(editable=False, max_length=8)),
                ('types', models.CharField(choices=[('FOOD', 'FOOD'), ('BAR', 'BAR'), ('COFFEE', 'COFFEE')], default='FOOD', max_length=8)),
                ('sub_type', models.CharField(default='', max_length=30, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=20)),
                ('is_redeem', models.BooleanField(default=False)),
                ('watch_later', models.BooleanField(default=False)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.Bill')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productapp.Coupon')),
            ],
            options={
                'db_table': 'voucher',
                'ordering': ['-created_at'],
            },
        ),
    ]
