# Generated by Django 2.2.8 on 2021-03-24 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210318_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Allowed characters are - , ' and alphanumeric characters", regex="^[\\'a-zA-Z0-9\\s,-]*$")]),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tag',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Allowed characters are - , ' and alphanumeric characters", regex="^[\\'a-zA-Z0-9\\s,-]*$")]),
        ),
    ]
