# Generated by Django 2.2.8 on 2021-03-21 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_auto_20210321_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='((?=.*[a-z])(?=.*[A-Z]))|((?=.*[A-Z])(?=.*[a-z]))|(?=.*[a-z])|(?=.*[A-Z])')]),
        ),
    ]
