# Generated by Django 2.2.8 on 2021-03-23 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0015_auto_20210321_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Allowed characters are - , ' and alphanumeric characters", regex="^[\\'a-zA-Z0-9\\s,-]*$")]),
        ),
    ]
