# Generated by Django 2.2.8 on 2021-03-17 06:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=10)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_service_charge', models.BooleanField(default=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payable_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('is_credit', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(editable=False, max_length=8)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('custom_discount_percentage', models.PositiveIntegerField(default=0)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('ret_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('custom_discount_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rate', models.PositiveIntegerField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('START_COOKING', 'START_COOKING'), ('SERVED', 'SERVED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=20)),
                ('customer_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('new', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cooking', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('served', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cancelled', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistoryBills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('net_paid_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('payment_mode', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=10)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderapp.Bills')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_scan_log', to='company.Asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW_ORDER', 'New Order'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('BILLABLE', 'Billable'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW_ORDER', max_length=12)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('custom_discount_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('custom_discount_amount', models.PositiveIntegerField(default=0)),
                ('is_service_charge', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='company.Asset')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orderapp.Bills')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='company.Company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
