# Generated by Django 2.2.8 on 2020-12-08 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0011_auto_20201203_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_scan_log', to='commonapp.Asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
