# Generated by Django 2.2.8 on 2021-01-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20210102_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
