# Generated by Django 2.2.8 on 2021-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20210322_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custom_discount_percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
