# Generated by Django 2.2.8 on 2021-01-04 08:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_bills_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
