# Generated by Django 2.2.8 on 2021-03-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_deliverypartner'),
        ('orderapp', '0005_auto_20210324_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='takeaway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='company.DeliveryPartner'),
        ),
    ]
