# Generated by Django 2.2.8 on 2021-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_orders_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='custom_discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NEW_ORDER', 'New Order'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('BILLABLE', 'Billable'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW_ORDER', max_length=12),
        ),
    ]
