# Generated by Django 2.2.8 on 2021-04-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_complimentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complimentary',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderapp.Orders'),
        ),
    ]
