# Generated by Django 2.2.8 on 2021-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_auto_20210112_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='custom_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
