# Generated by Django 2.2.8 on 2021-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_orders_custom_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
