# Generated by Django 2.2.8 on 2021-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_auto_20210129_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20),
        ),
    ]
