# Generated by Django 2.2.8 on 2021-02-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0013_auto_20210207_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='payment_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH')], default='CASH', max_length=10),
        ),
    ]
