# Generated by Django 2.2.8 on 2021-02-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_customer'),
        ('orderapp', '0014_auto_20210207_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='userapp.Customer'),
        ),
    ]
