# Generated by Django 2.2.8 on 2021-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0016_auto_20210207_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20),
        ),
    ]
