# Generated by Django 2.2.8 on 2021-02-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0017_auto_20210209_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='payment_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT')], default='CASH', max_length=10),
        ),
    ]
