# Generated by Django 2.2.8 on 2021-02-16 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0018_auto_20210212_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bills',
            name='ret_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='TransactionHistoryBills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('net_paid_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderapp.Bills')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
