# Generated by Django 2.2.8 on 2021-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0019_auto_20210216_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='custom_discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='custom_discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
