# Generated by Django 2.2.8 on 2021-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0021_auto_20210217_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistorybills',
            name='payment_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT')], default='CASH', max_length=10),
        ),
    ]
