# Generated by Django 2.2.8 on 2021-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0022_transactionhistorybills_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='cancelled',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
