# Generated by Django 2.2.8 on 2021-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0023_orderlines_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
