# Generated by Django 2.2.8 on 2021-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0024_auto_20210228_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
