# Generated by Django 2.2.8 on 2021-02-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0025_auto_20210228_1324'),
        ('orderapp', '0025_auto_20210228_1504'),
    ]

    operations = [
    ]
