# Generated by Django 2.2.8 on 2021-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0027_orderlines_customer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='payment_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionhistorybills',
            name='payment_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=10),
        ),
    ]
