# Generated by Django 2.2.8 on 2021-03-14 06:42

import commonapp.models.image
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.app_helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='affiliate/')),
                ('description', models.TextField()),
                ('discount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('deal_of_the_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'affiliate_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('ROOM', 'ROOM'), ('TABLE', 'TABLE')], default='ROOM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^(\\+?[\\d]{2,3}\\-?)?[\\d]{8,10}$')])),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('payment_mode', models.CharField(choices=[('Card', 'Card Payment'), ('Cash', 'Cash Payment')], default='Cash', max_length=10)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('invoice_number', models.CharField(editable=False, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon', models.FileField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('token', models.CharField(blank=True, editable=False, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=30)),
                ('zip_code', models.CharField(blank=True, default='', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('logo_icon', models.ImageField(blank=True, null=True, upload_to=helpers.app_helpers.content_file_name)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+?[\\d]{2,3}\\-?)?[\\d]{8,10}$')])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_affiliate', models.BooleanField(default=False)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('key', models.CharField(max_length=8)),
                ('currency', models.CharField(max_length=10)),
                ('invoice_counter', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(default='', max_length=16)),
                ('print_tax_invoice', models.BooleanField(default=True)),
                ('print_pre_order_bill', models.BooleanField(default=False)),
                ('print_order', models.BooleanField(default=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('deal_of_the_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_qr_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'company users',
                'db_table': 'company_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facility',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'favourite companies',
                'db_table': 'favourite_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=commonapp.models.image.Image.get_upload_path)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^(\\+?[\\d]{2,3}\\-?)?[\\d]{8,10}$')])),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('is_billed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW_ORDER', 'New Order'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('BILLABLE', 'Billable'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW_ORDER', max_length=12)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('START_COOKING', 'START_COOKING'), ('SERVED', 'SERVED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_line',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Category')),
            ],
            options={
                'verbose_name_plural': 'sub categories',
                'db_table': 'sub_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company')),
            ],
            options={
                'db_table': 'social_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapp.Bill')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapp.OrderLine')),
            ],
            options={
                'db_table': 'sales_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
