# Generated by Django 2.2.8 on 2021-03-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productapp.Product'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productapp.Voucher'),
        ),
        migrations.AddField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_rating', to='commonapp.Company'),
        ),
    ]
