# Generated by Django 2.2.2 on 2020-07-28 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
