# Generated by Django 2.2.8 on 2020-11-05 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Category'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapp.Bill'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapp.Order'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.Product'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.Voucher'),
        ),
        migrations.AddField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.BulkQuantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Asset'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Product'),
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='favouritecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='favouritecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_category', to='commonapp.Category'),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.SubCategory'),
        ),
        migrations.AddField(
            model_name='bulkquantity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Category'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.SubCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_code', 'company')},
        ),
    ]
