# Generated by Django 2.2.2 on 2020-10-11 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
