# Generated by Django 2.2.2 on 2020-10-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_auto_20201011_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
