# Generated by Django 2.2.8 on 2021-03-14 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('productapp', '0001_initial'),
        ('commonapp', '0002_auto_20210314_1227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productapp.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Asset'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapp.Bill'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.Voucher'),
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='favouritecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='favouritecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_category', to='commonapp.Category'),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.SubCategory'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commonapp.Category'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affilated_companies', to='commonapp.Company'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commonapp.SubCategory'),
        ),
    ]
