# Generated by Django 2.2.8 on 2020-11-11 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_auto_20201109_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='save_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
