# Generated by Django 2.2.2 on 2020-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0003_coupon_deal_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='asd43', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_code', 'company')},
        ),
    ]
