# Generated by Django 2.2.8 on 2020-11-20 15:53

from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0004_company_logo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], default='FLAT', max_length=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=30, null=True, validators=[helpers.validators.is_alphabetic]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(validators=[helpers.validators.is_positive_float]),
        ),
    ]
