# Generated by Django 2.2.8 on 2020-11-20 17:00

from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0005_auto_20201120_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=30, null=True, validators=[helpers.validators.is_alphanumeric_with_exception]),
        ),
    ]
