# Generated by Django 2.2.8 on 2020-11-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0006_auto_20201120_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_rating', to='commonapp.Company'),
        ),
    ]
