# Generated by Django 2.2.8 on 2020-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0008_auto_20201123_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_veg',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_currency',
            field=models.CharField(choices=[('NRS', 'NRS'), ('INR', 'INR'), ('USD', 'USD')], default='NRS', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_currency',
            field=models.CharField(choices=[('NRS', 'NRS'), ('INR', 'INR'), ('USD', 'USD')], default='NRS', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8),
        ),
    ]
