# Generated by Django 2.2.8 on 2020-12-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affilated_companies', to='commonapp.Company'),
        ),
    ]
