# Generated by Django 2.2.8 on 2020-12-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0011_auto_20201203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_coupons', to='commonapp.Company'),
        ),
    ]
