# Generated by Django 2.2.8 on 2020-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0012_auto_20201213_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
