# Generated by Django 2.2.8 on 2020-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0013_auto_20201215_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'company')},
        ),
    ]
