# Generated by Django 2.2.8 on 2020-12-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0014_auto_20201215_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
