# Generated by Django 2.2.8 on 2020-12-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0015_auto_20201216_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ROOM', 'ROOM'), ('TABLE', 'TABLE')], default='ROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='state',
            field=models.CharField(choices=[('NEW', 'NEW'), ('START_COOKING', 'START_COOKING'), ('SERVED', 'SERVED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=20),
        ),
    ]
