# Generated by Django 2.2.8 on 2020-12-22 12:43

from django.db import migrations, models
import helpers.app_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0017_auto_20201222_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=helpers.app_helpers.content_file_name),
        ),
    ]
