# Generated by Django 2.2.8 on 2020-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0018_auto_20201222_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
