# Generated by Django 2.2.8 on 2021-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0021_auto_20210107_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_qr_user',
            field=models.BooleanField(default=False),
        ),
    ]
