# Generated by Django 2.2.8 on 2021-02-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0026_auto_20210131_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
