# Generated by Django 2.2.8 on 2021-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0026_auto_20210131_1137'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='productcategory',
    #         name='position',
    #         field=models.PositiveIntegerField(blank=True, default=0)
    #     ),
    # ]
