# Generated by Django 2.2.8 on 2021-02-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0027_productcategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
