# Generated by Django 2.2.8 on 2021-02-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0029_auto_20210204_1315'),
        ('commonapp', '0028_auto_20210201_1149'),
    ]

    operations = [
    ]
