# Generated by Django 2.2.8 on 2021-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0030_merge_20210205_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sub_type',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
