# Generated by Django 2.2.8 on 2021-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0031_auto_20210205_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='types',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('BAR', 'BAR'), ('COFFEE', 'COFFEE')], default='FOOD', max_length=5),
        ),
    ]
