# Generated by Django 2.2.8 on 2021-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0033_auto_20210205_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
