# Generated by Django 2.2.8 on 2021-02-09 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0034_companyuser_is_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
