# Generated by Django 2.2.8 on 2021-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0037_auto_20210211_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='print_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='print_pre_order_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='print_tax_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
