# Generated by Django 2.2.8 on 2021-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0040_auto_20210221_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
