# Generated by Django 2.2.8 on 2021-01-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0021_auto_20210107_1325'),
        ('notifications', '0002_auto_20210103_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapp.Asset'),
        ),
    ]
